name: Tests

on:
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable
    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=$(google-chrome --version | sed -E 's/.+\((.*)\)/\1/')
        wget --no-verbose -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run:
        pytest